CREATE DATABASE member DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;


USE member;


CREATE TABLE member (
  id VARCHAR(20) NOT NULL PRIMARY KEY,
  name VARCHAR(5) NOT NULL,
  age INT(2),
  gender VARCHAR(2) NOT NULL,
  email VARCHAR(50),
  promotion VARCHAR(2) NOT NULL DEFAULT 'x'
);